[workspace]
resolver = "3"

members = [
    "crates/experimentation-1",
    "crates/experimentation-2",
    "ioboard/firmware-stm32h743zi",
    "ioboard/ioboard-main",
    "ioboard/ioboard-net",
    "ioboard/ioboard-trace",
]
