name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install libdbus
      run: sudo apt-get install -y libdbus-1-3 libdbus-1-dev
    - name: Build (firmware-stm32h743zi)
      run: cd ioboard/firmware-stm32h743zi && cargo build --verbose
